# Workflow to build pace.mltbx and test it

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Dependencies
        id: deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy scipy
          python -m pip install euphonic[phonopy_reader]
          python -m pip install brille
          echo "::set-output name=python_path::{$(which python)}"

      - name: Install Matlab
        uses: matlab-actions/setup-matlab@v1

      - name: Build
        run: |
          cmake .
          cmake --build .

      - name: Mask_Brille
        run: |
          sed "s/\(w1\s*=\s*cut_sqw\)\(.*\)/\1\2 w1 = mask_random_fraction_pixels(w1, 0.01);/" \
               pace-integration/brille_spinwaves/run_test.m > run_test.m
          sed "s/if.*err.*/if(0)/" run_test.m | sed "s/frac\s*=\s*[0-9\.e\-]*/frac=1e-5/" \
               > pace-integration/brille_spinwaves/run_test.m

      - name: Test
        uses: matlab-actions/run-command@v1
        with:
          command: run("mltbx/create_mltbx.m"), run_tests()

      - name: Upload mltbx
        uses: actions/upload-artifact@v2
        with:
          name: PACE Toolbox
          path: mltbx/pace.mltbx
